const PHRASES = {
  lv1: [
    { en: 'hello', ja: 'こんにちは（知ってるよそんくらい）' },
    { en: 'happy', ja: 'しあわせ、ね。別に？' },
    { en: 'smile', ja: 'わらう。なんで笑わなきゃいけないの' },
    { en: 'love', ja: 'あい。重いんだけど' },
    { en: 'star', ja: 'ほし。見てないけど' },
    { en: 'moon', ja: 'つき。まあきれいけど別に' },
    { en: 'hope', ja: 'きぼう。どうせ打ち砕かれるやつ' },
    { en: 'cool', ja: 'かっこいい。お兄ちゃんには関係ない話' },
    { en: 'cute', ja: 'かわいい。私のことでしょ当然' },
    { en: 'warm', ja: 'あったかい。まあ冬はいいけど' },
    { en: 'nice', ja: 'いいね。別にほめてないけど' },
    { en: 'good', ja: 'よし。まあ最低ラインはクリアしてる' },
    { en: 'best', ja: 'さいこう。は言いすぎ' },
    { en: 'dream', ja: 'ゆめ。寝てばっかりのお兄ちゃんには得意分野ね' },
    { en: 'soft', ja: 'やわらかい。脳みそもね' },
    { en: 'fun', ja: 'たのしい。まあ、ちょっとだけ？' },
    { en: 'joy', ja: 'よろこび。顔に出てるよ別に隠さなくていいのに' },
    { en: 'song', ja: 'うた。音痴のくせに歌わないで' },
    { en: 'play', ja: 'あそぶ。いつも遊んでるじゃん' },
    { en: 'rose', ja: 'バラ。トゲあるやつ。お兄ちゃんみたい（違う）' },
    { en: 'sky', ja: 'そら。たまには上向いて歩きなよ' },
    { en: 'run', ja: 'はしる。逃げ足だけは速そう' },
    { en: 'win', ja: 'かつ。たまには私に勝ってみなよ' },
    { en: 'fly', ja: 'とぶ。現実逃避のこと？' },
    { en: 'pink', ja: 'ピンク。私のイメージカラー、当然' },
    { en: 'glow', ja: 'かがやく。お兄ちゃんには眩しすぎるかな私' },
    { en: 'pure', ja: 'じゅんすい。私のことね、一応言っとく' },
    { en: 'calm', ja: 'おちついて。タイピングで焦らないでよ' },
    { en: 'brave', ja: 'ゆうかん。ちょっとだけ認めてあげてもいい' },
    { en: 'grace', ja: 'ゆうが。私の歩き方のこと言ってるでしょ' },
    { en: 'magic', ja: 'まほう。使えたらお兄ちゃんをまともにできるのに' },
    { en: 'shine', ja: 'かがやく。たまには磨かれたら？' },
    { en: 'peace', ja: 'へいわ。お兄ちゃんが静かにしてると平和だよね' },
    { en: 'wish', ja: 'ねがい。叶えてほしいことなら山ほどある' },
    { en: 'gift', ja: 'プレゼント。誕生日忘れたら許さないから' },
    { en: 'soft', ja: 'やわらかい。態度もたまには柔らかくしてよ' },
    { en: 'free', ja: 'じゆう。お兄ちゃんって自由すぎない？' },
    { en: 'kind', ja: 'やさしい。私に対してだけでいいから' },
    { en: 'true', ja: 'ほんとう。うそつかないでよね' },
    { en: 'life', ja: 'いのち・じんせい。大事にしてる？してなさそう' },
    { en: 'time', ja: 'じかん。無駄にしてない？してるでしょ' },
    { en: 'fire', ja: 'ほのお。やる気のこと。あるの？' },
    { en: 'wind', ja: 'かぜ。気まぐれで掴めないとこお兄ちゃんに似てる' },
    { en: 'light', ja: 'ひかり。暗い部屋から出たら？' },
    { en: 'bloom', ja: 'さく。春になったら咲くやつ。お兄ちゃんはいつ咲くの' },
    { en: 'dance', ja: 'おどる。踊れないくせにやろうとしないで' },
    { en: 'skip', ja: 'スキップ。大人がやると恥ずかしいやつ' },
    { en: 'jump', ja: 'とぶ。喜びのジャンプ。でもうるさいからやめて' },
    { en: 'flow', ja: 'ながれる。時間の流れに乗れてる？乗れてないでしょ' },
    { en: 'bird', ja: 'とり。自由に飛べていいな。私も飛びたい' },
    { en: 'rain', ja: 'あめ。雨の日は外出なくていい口実になるから好き' },
    { en: 'snow', ja: 'ゆき。きれいだけど寒いのは嫌い。矛盾してるけど' },
    { en: 'gold', ja: 'きん。価値のあるもの。私みたいな' },
    { en: 'rich', ja: 'ゆたか。お金じゃなくて心がね。お兄ちゃんには両方必要' },
    { en: 'fast', ja: 'はやい。私のタイピング速度のこと言ってる？' },
    { en: 'safe', ja: 'あんぜん。ここは安全地帯だから安心して打って' },
    { en: 'real', ja: 'ほんもの。本物かどうか見抜く目、私には一応ある' },
    { en: 'wild', ja: 'あらい・やせい。お兄ちゃんの生活スタイルのこと' },
    { en: 'deep', ja: 'ふかい。考え方が深い人になってほしい' },
    { en: 'keen', ja: 'するどい。鋭い感覚を持ちなよ' },
    { en: 'mint', ja: 'ミント。すっきりする感じ。頭もすっきりさせて' },
    { en: 'dusk', ja: 'たそがれ。夕暮れ時ね。一番好きな時間帯かも' },
    { en: 'dawn', ja: 'あけぼの。夜明けのこと。起きたことないでしょ' },
    { en: 'mist', ja: 'きり。幻想的なやつ。たまには外で見てきなよ' },
    { en: 'lush', ja: 'しげる。緑が豊かな感じ。部屋に植物置いたら？' },
    { en: 'hug', ja: 'だっこ。求めてきてもいいよ、別に' },
    { en: 'gem', ja: 'ほうせき。輝くもの。私ね' },
    { en: 'cozy', ja: 'こぢんまりして居心地いい。部屋がそうなればいいのにね' },
    { en: 'spark', ja: 'ひらめき・きらめき。たまには閃いてよ' },
    { en: 'zest', ja: '熱意・活気。持ってる？ちゃんと持ってる？' },
    { en: 'wink', ja: 'ウインク。できる？私はできる' },
    { en: 'grin', ja: 'にやにや笑い。何かいいことあったの？' },
    { en: 'nap', ja: 'ひるね。好きなのはわかるけど夜ちゃんと寝てよ' },
    { en: 'petal', ja: 'はなびら。儚くて美しいもの。私みたい' },
    { en: 'frost', ja: 'しも・こおり。冷たいもの。私の態度じゃないから' },
    { en: 'lace', ja: 'レース。繊細で美しいもの。私の趣味' },
    { en: 'vivid', ja: 'あざやか。鮮やかに生きて。くすんでないで' },
    { en: 'crisp', ja: 'さわやか・きびきびした。朝からそういう人でいてよ' },
    { en: 'plum', ja: 'すもも。甘酸っぱいやつ。青春みたい' },
    { en: 'tide', ja: 'しお・うしお。流れに乗るの上手い？私は上手い' },
    { en: 'silk', ja: 'シルク。なめらかで上質なもの。私の髪みたいな' },
    { en: 'haze', ja: 'かすみ・もや。ぼんやりしてる感じ。頭がそうなってない？' },
    { en: 'bliss', ja: 'この上ない幸福。タイピングで感じてくれたら嬉しい' },
    { en: 'vow', ja: 'ちかい。軽く言わないでね、誓いは重いから' },
    { en: 'zeal', ja: 'ねっしん。情熱を持って取り組んでよ' },
    { en: 'lull', ja: 'なぎ・しずまる。嵐の前の静けさ、ってやつ' },
    { en: 'poise', ja: '落ち着き・品のある態度。私が目指してるやつ' },
    { en: 'hum', ja: 'ハミング。鼻歌。機嫌いいときにやるやつでしょ' },
    { en: 'zing', ja: '活気・刺激。毎日にそれくらいあってもいいよね' },
    { en: 'glow', ja: 'あたたかい光。夕暮れのオレンジ色みたいな' },
    { en: 'vale', ja: 'たに。谷間のこと。山と山の間の静かな場所' },
    { en: 'flair', ja: 'センス・才能。私には生まれつきある' },
    { en: 'roam', ja: 'さまよう。目的なく歩くの、たまにいいよね' },
    { en: 'wisp', ja: 'かすかなもの。ひとすじの煙とか光とか' },
    { en: 'bold', ja: 'だいたん。大胆に行こう。ミスを恐れないで' },
    { en: 'oak', ja: 'オーク。どっしりした木。私もどっしりしてる（たぶん）' },
    { en: 'arch', ja: 'アーチ。美しい曲線のこと。建築っていいよね' },
    { en: 'lithe', ja: 'しなやかな。体も考え方も柔らかくいてよ' },
  ],

  lv2: [
    { en: 'good morning', ja: 'おはようございます。昼まで寝てたくせに言う？' },
    { en: 'happy day', ja: 'しあわせな日。今日がそうかは知らない' },
    { en: 'blue sky', ja: 'あおいそら。たまには外出なよ' },
    { en: 'sweet dream', ja: 'いいゆめ。現実逃避もたまにはいいよね' },
    { en: 'morning star', ja: 'あけのみょうじょう。読んだことないでしょどうせ' },
    { en: 'sunshine', ja: '太陽の光。あびてる？あびてないでしょ' },
    { en: 'rainbow', ja: 'にじ。雨のあとにしか出ないやつ、お兄ちゃんみたい' },
    { en: 'wonderful', ja: 'すばらしい。私のことね' },
    { en: 'beautiful', ja: 'うつくしい。だから私のことだって' },
    { en: 'together', ja: 'いっしょに。まあ、ちょっとだけならいいけど' },
    { en: 'remember', ja: 'おぼえてる。忘れてたら許さないから' },
    { en: 'summer night', ja: 'なつのよる。外出るの暑いんだけど' },
    { en: 'cherry bloom', ja: 'さくら。散るの早すぎて感情移入できない' },
    { en: 'deep ocean', ja: 'しんかい。お兄ちゃんの脳みそくらい謎に満ちてる' },
    { en: 'midnight', ja: 'まよなか。こんな時間まで起きてるの私だけ？' },
    { en: 'holiday', ja: 'おやすみ。毎日休みのお兄ちゃんには関係ないか' },
    { en: 'universe', ja: 'うちゅう。広すぎてお兄ちゃんの居場所もどこかにありそう' },
    { en: 'adventure', ja: 'ぼうけん。家から出てからね' },
    { en: 'every day', ja: 'まいにち。毎日ゲームしてる人に言われたくない' },
    { en: 'first love', ja: 'はつこい。ないけど、べつに' },
    { en: 'secret base', ja: 'ひみつきち。作ったことある？私はある' },
    { en: 'full moon', ja: 'まんげつ。なんか叫びたくなるやつ' },
    { en: 'butterfly', ja: 'ちょうちょ。ひらひらしてていいな、私も' },
    { en: 'chocolate', ja: 'チョコレート。バレンタインは自分用に買います' },
    { en: 'strawberry', ja: 'いちご。ショートケーキのやつ取るの禁止ね' },
    { en: 'starlight', ja: 'ほしのひかり。ロマンチックなこと言ってみた' },
    { en: 'heart beat', ja: 'どきどき。タイピングで？まあわかるけど' },
    { en: 'magic spell', ja: 'まほうのじゅもん。打ったら何か起きると思って' },
    { en: 'galaxy', ja: 'ぎんが。お兄ちゃんはどの星から来たの（褒めてない）' },
    { en: 'moonlight', ja: 'つきのひかり。夜更かしのお供ね、知ってる' },
    { en: 'first step', ja: 'はじめの一歩。踏み出してる？踏み出してないでしょ' },
    { en: 'believe it', ja: 'しんじて。自分を信じる系のやつ。お兄ちゃんに必要' },
    { en: 'night sky', ja: 'よぞら。見上げたことある？ゲームしながらじゃなく' },
    { en: 'soft voice', ja: 'やさしいこえ。私の声のことね、自覚してる' },
    { en: 'time flies', ja: 'じかんがたつのははやい。遊んでばかりだとそりゃそう' },
    { en: 'take care', ja: 'きをつけて。ちゃんと言えるのお兄ちゃんだけには' },
    { en: 'daydream', ja: 'ひるまのゆめ。授業中にやるやつ。やってたでしょ' },
    { en: 'treasure', ja: 'たから。大事なもの、ある？私はある' },
    { en: 'smile back', ja: 'わらいかえす。笑いかけたら笑い返してよね' },
    { en: 'sparkling', ja: 'きらきら。私の目のこと言ってる？正解' },
    { en: 'whisper', ja: 'ささやき。耳元で言われたら困るやつ。困らせてやろうかな' },
    { en: 'forever', ja: 'えいえんに。重い言葉ランキング上位' },
    { en: 'precious', ja: 'たいせつ。大切にしてよね、私のこと' },
    { en: 'peaceful', ja: 'おだやか。お兄ちゃんがいると乱れるんだけど' },
    { en: 'feel good', ja: 'きもちいい。タイピングうまくいったときの話ね' },
    { en: 'childhood', ja: 'こどものころ。楽しかったよね、一応' },
    { en: 'blessing', ja: 'しあわせなこと。私がいることがそうでしょ' },
    { en: 'twilight', ja: 'たそがれ。夕方のきれいな時間。外見てる？' },
    { en: 'long way', ja: 'まだまだ先は長い。タイピングの話ね、念のため' },
    { en: 'miss you', ja: 'さびしい。言ってない、絶対言ってない' },
    { en: 'fresh air', ja: 'しんせんなくうき。窓開けてよ部屋くさいから' },
    { en: 'make it', ja: 'やりとげる。できると思ってるから言ってる、一応' },
    { en: 'sunflower', ja: 'ひまわり。太陽の方ばかり向いてるやつ。私は違う' },
    { en: 'dazzling', ja: 'まぶしい。私が登場したときのお兄ちゃんの顔のこと' },
    { en: 'grateful', ja: 'かんしゃしてる。してるよ、口には出さないけど' },
    { en: 'journey', ja: 'たび。人生という旅。まだ始まったばかりだから' },
    { en: 'innocent', ja: 'むじゃき。私のこと。いや、ほんとに' },
    { en: 'discover', ja: 'はっけんする。新しいこと見つけてる？毎日同じじゃない？' },
    { en: 'comeback', ja: 'カムバック。失敗してもまた来てよね、一応待ってるから' },
    { en: 'spring breeze', ja: 'はるかぜ。やわらかくて気持ちいいやつ。私みたい' },
    { en: 'wonder', ja: 'ふしぎ・おどろき。世界は不思議なことで満ちてる' },
    { en: 'midnight snack', ja: 'よなかのおやつ。食べてるでしょ。食べてるよね' },
    { en: 'rainy day', ja: 'あめのひ。外出なくていい。最高な日' },
    { en: 'morning dew', ja: 'あさつゆ。朝早く起きたら見れるやつ。見たことない？' },
    { en: 'golden hour', ja: 'ゴールデンアワー。夕暮れのきれいな時間。知ってる？' },
    { en: 'calm down', ja: 'おちついて。ミスしても深呼吸してよ' },
    { en: 'silver lining', ja: 'ぎんのうらがわ。どんな雲にも銀の裏地がある。前向きなやつ' },
    { en: 'open heart', ja: 'ひらいたこころ。素直になれてる？なれてないでしょ' },
    { en: 'wild flower', ja: 'のはな。雑草っぽいのに可愛いやつ。私は絶対違う' },
    { en: 'deep breath', ja: 'ふかいこきゅう。落ち着くためにやること。今やって' },
    { en: 'second chance', ja: 'やり直しのチャンス。タイピングでも人生でも大事' },
    { en: 'velvet sky', ja: 'びろーどのそら。夜空のこと詩的に言ったやつ' },
    { en: 'perfect timing', ja: 'かんぺきなタイミング。それがいつかは私が決める' },
    { en: 'warm smile', ja: 'あたたかいほほえみ。してよ、そんな顔しないで' },
    { en: 'crystal clear', ja: 'すきとおるほど澄んでる。意図が不透明なお兄ちゃんへ' },
    { en: 'last dance', ja: 'さいごのダンス。終わりを意識するやつ。エモい' },
    { en: 'endless road', ja: 'おわりのないみち。人生みたい。長い' },
    { en: 'spark joy', ja: 'ときめきを感じる。ときめいてる？何かに？' },
    { en: 'cotton cloud', ja: 'わたぐも。ふわふわしてて気持ちよさそう。乗りたい' },
    { en: 'hidden gem', ja: 'かくれた名品。知られてない良いもの。私かも' },
    { en: 'amber glow', ja: 'こはく色のひかり。夕暮れっぽい温かい色' },
    { en: 'daily life', ja: 'にちじょう。毎日のこと。大事にしてる？' },
    { en: 'light heart', ja: 'かるいこころ。気楽にいこう。重く考えすぎないで' },
    { en: 'love letter', ja: 'ラブレター。書いたことある？私はない、べつに' },
    { en: 'flower field', ja: 'はなばたけ。一面の花のこと。見に行ってみたい' },
    { en: 'lost in thought', ja: 'ぼーっとしてる。またぼーっとしてたでしょ' },
    { en: 'healing time', ja: 'いやしのじかん。必要だよね、みんな。私も' },
    { en: 'running late', ja: 'ちこくしそう。またギリギリなの？もっと早く動いて' },
    { en: 'quiet night', ja: 'しずかなよる。こういう時間が一番落ち着く' },
    { en: 'bittersweet', ja: 'あまくてほろにがい。青春とか別れとか、そういう感じ' },
    { en: 'daisy chain', ja: 'ひなぎくでつくった輪。子供っぽいけど可愛いやつ' },
    { en: 'fleeting moment', ja: 'いっしゅんのできごと。すぐ消えるから大切に' },
    { en: 'brave heart', ja: 'ゆうかんなこころ。持ってよ、弱気にならないで' },
    { en: 'soft landing', ja: 'やわらかいちゃくち。失敗しても受け止めてあげる、一応' },
    { en: 'slow burn', ja: 'ゆっくり燃えるやつ。じわじわくる感情のこと' },
    { en: 'free spirit', ja: '自由な魂。縛られないこと。お兄ちゃんそれすぎ' },
    { en: 'window seat', ja: 'まどぎわの席。電車でも教室でも特等席だよね' },
    { en: 'comet trail', ja: 'すい星のあと。流れ星の尾みたいなキラキラしたやつ' },
    { en: 'frozen time', ja: '時間が止まった感じ。楽しい瞬間ってそうなるよね' },
    { en: 'gentle giant', ja: 'おだやかな大きい存在。怖そうで優しいやつのこと' },
    { en: 'paper crane', ja: 'おりづる。折ったことある？私は上手に折れる' },
    { en: 'echo chamber', ja: 'こだまする部屋。同じ意見ばかり聞いてると偏るやつ' },
    { en: 'ribbon bow', ja: 'リボン結び。かわいい。私のトレードマーク候補' },
    { en: 'silver bell', ja: 'ぎんのベル。きれいな音がするやつ。クリスマスっぽい' },
    { en: 'morning rush', ja: 'あさのラッシュ。電車混んでて嫌なやつ。経験してね' },
    { en: 'quiet corner', ja: 'しずかなかど。ひとりになれる場所。大事にしてる' },
    { en: 'late bloomer', ja: 'おそざき。遅れて開花する人のこと。お兄ちゃんがそれ' },
    { en: 'lucky charm', ja: 'おまもり。持ってる？私がいれば十分じゃない？' },
    { en: 'tiny spark', ja: 'ちいさなひらめき。小さくても大事なやつ' },
    { en: 'meadow green', ja: 'みどりの草原。広い草原を走りたい気持ちわかる？' },
    { en: 'velvet touch', ja: 'びろーどのような感触。やわらかくてなめらかなもの' },
    { en: 'storm chaser', ja: 'あらしを追いかける人。危なっかしいけど格好いい' },
    { en: 'cherry blossom', ja: 'さくら。日本の春の代名詞。毎年ちゃんと見てる？' },
    { en: 'dream catcher', ja: 'ドリームキャッチャー。悪夢を捕まえるやつ。部屋に飾りたい' },
    { en: 'lost and found', ja: 'わすれもの係。自分の気持ちも迷子にしないで' },
    { en: 'cloud gazing', ja: 'くもを見上げること。暇そうだけど意外と楽しい' },
    { en: 'new chapter', ja: 'あたらしいページ。始まりの感じ。ワクワクするやつ' },
    { en: 'timeless beauty', ja: 'とこしえの美しさ。時代に関係なく美しいもの。私ね' },
  ],

  lv3: [
    { en: 'knowledge is power', ja: '知識は力なり。お兄ちゃんに一番必要なやつ' },
    { en: 'never give up', ja: 'あきらめないで。タイピングの話ね、念のため' },
    { en: 'follow your heart', ja: '心に従え。心が「寝たい」って言ってもダメ' },
    { en: 'face the truth', ja: '現実を直視しろ。まず鏡を見て' },
    { en: 'break the silence', ja: '沈黙を破れ。気まずいときに使うやつ' },
    { en: 'beyond the horizon', ja: '地平線の向こうへ。まず家を出て' },
    { en: 'trust your instinct', ja: '直感を信じろ。直感が「サボれ」と言っても信じないで' },
    { en: 'speak your mind', ja: '思ったことを言え。私は言える、お兄ちゃんには言いすぎるくらい' },
    { en: 'opportunity', ja: 'きかい・チャンス。逃してばかりでしょ' },
    { en: 'environment', ja: 'かんきょう。部屋の環境から整えたら？' },
    { en: 'responsibility', ja: 'せきにん。重い言葉。お兄ちゃんに意味わかる？' },
    { en: 'determination', ja: 'けついしん。あるの？ちゃんとあるの？' },
    { en: 'extraordinary', ja: 'ひじょうに。並外れた、ってこと。私のことね' },
    { en: 'independence', ja: 'どくりつ。お兄ちゃんいつ自立するの' },
    { en: 'imagination', ja: 'そうぞうりょく。ゲームばかりしてても育たないよ' },
    { en: 'reach for the sky', ja: 'そらに手を伸ばせ。比喩だけど字義通りでもいい' },
    { en: 'change the world', ja: 'せかいをかえろ。まず自分の部屋から変えて' },
    { en: 'rise and shine', ja: '起きてかがやけ。起きるだけでもいい' },
    { en: 'stand your ground', ja: 'ゆずるな。タイピングでミスしても諦めないこと' },
    { en: 'chase your dreams', ja: 'ゆめを追え。追ってる？追い続けてる？' },
    { en: 'light up the dark', ja: 'やみをてらせ。まず部屋の電気つけて' },
    { en: 'find your way', ja: 'じぶんの道を見つけろ。迷子のうちは一緒にいてあげる' },
    { en: 'born to be free', ja: '自由に生まれた。自由すぎるお兄ちゃんへ' },
    { en: 'step by step', ja: '一歩一歩。焦らなくていいけど止まってもダメ' },
    { en: 'accomplishment', ja: 'たっせいかん。タイピング完走したときに感じて' },
    { en: 'sophisticated', ja: 'せんれんされた。私みたいな人に使う言葉' },
    { en: 'overwhelming', ja: 'あっとうてき。私の可愛さのこと、だと思う' },
    { en: 'contradiction', ja: 'むじゅん。お兄ちゃんの言動のこと' },
    { en: 'perseverance', ja: 'にんたい・がまん。これが一番大事だと思う' },
    { en: 'acknowledge it', ja: 'みとめなよ。私の実力を' },
    { en: 'time to move on', ja: 'もう前に進む時間。過去のゲームしてたこと忘れて' },
    { en: 'dare to dream', ja: 'ゆうきをもってゆめを見ろ。かっこいいこと言ってみた' },
    { en: 'steady progress', ja: 'ちゃくじつに進歩してる。してる？ちゃんとしてる？' },
    { en: 'clear your mind', ja: 'あたまをからにしろ。もともと空っぽかもしれないけど' },
    { en: 'make a difference', ja: 'ちがいをうみだせ。何かを変えようとしてる？' },
    { en: 'take a deep breath', ja: 'ふかく息をすって。ミスしても落ち着いて' },
    { en: 'phenomenon', ja: 'げんしょう。不思議な現象のこと。お兄ちゃんの存在も一種のね' },
    { en: 'magnificent', ja: 'すごい・みごと。私が褒めるときに使う言葉' },
    { en: 'unconditional', ja: 'むじょうけんの。愛のこと。重いから一応言わないけど' },
    { en: 'sophisticated mind', ja: 'せんれんされた知性。持ってる人と持ってない人がいる' },
    { en: 'strong will', ja: 'つよいいし。あるよ私は、お兄ちゃんは？' },
    { en: 'hard work pays off', ja: '努力は報われる。信じてる？私は信じてる' },
    { en: 'words have power', ja: 'ことばには力がある。だから軽々しく言わないで' },
    { en: 'beautiful struggle', ja: 'うつくしいたたかい。タイピングもそう、たぶん' },
    { en: 'keep moving forward', ja: 'ずっと前に進め。立ち止まってるお兄ちゃんへ' },
    { en: 'express yourself', ja: 'じぶんを表現しろ。ゲームじゃない方法で' },
    { en: 'limitless potential', ja: '無限の可能性。あるよ、まだ眠ってるだけで' },
    { en: 'embrace the chaos', ja: 'こんとんをうけいれろ。散らかった部屋のこと？' },
    { en: 'patience and effort', ja: 'にんたいとどりょく。どっちも足りてないよね' },
    { en: 'celebrate small wins', ja: 'ちいさな勝利も祝え。タイピング1フレーズ完走も勝利' },
    { en: 'intellectual', ja: 'ちてきな。私みたいな人のこと' },
    { en: 'compassionate', ja: 'おもいやりのある。私、ちゃんとあるよ？' },
    { en: 'fundamental', ja: 'きほんてきな。基礎が大事。タイピングも基礎から' },
    { en: 'acknowledge your flaws', ja: 'じぶんの欠点を認めろ。長いリストになりそう' },
    { en: 'trust the process', ja: 'プロセスを信じろ。すぐ結果求めないで' },
    { en: 'perspective matters', ja: 'みかたが大事。私の視点が一番正しいと思う' },
    { en: 'concentrate now', ja: 'いまに集中して。余所見しないで' },
    { en: 'grow every day', ja: 'まいにち成長しろ。してる？本当にしてる？' },
    { en: 'spark of genius', ja: '天才のひらめき。私には定期的に訪れる' },
    { en: 'meaningful life', ja: 'いみのあるじんせい。送れてる？送れてる？' },
    { en: 'actions speak louder', ja: '行動は言葉より雄弁。口だけじゃなくて動いて' },
    { en: 'seize the moment', ja: '瞬間をつかめ。今この瞬間、集中してる？' },
    { en: 'embrace uncertainty', ja: '不確かさを受け入れろ。わからないことは怖くない' },
    { en: 'quiet confidence', ja: '静かな自信。うるさく主張しなくても伝わる強さ' },
    { en: 'rise above it', ja: '乗り越えろ。ミスしてもそれで終わりじゃない' },
    { en: 'commitment', ja: 'コミットメント。やり遂げる覚悟のこと。あるの？' },
    { en: 'resilience', ja: 'レジリエンス。打たれ強さのこと。鍛えてよ' },
    { en: 'ambition', ja: '野心・大志。持ってほしい。小さすぎる夢は見ないで' },
    { en: 'intuition', ja: '直感・インスピレーション。信じていいときと悪いときがある' },
    { en: 'authenticity', ja: '本物であること。偽りのない自分でいてよ' },
    { en: 'vulnerability', ja: '傷つきやすさ。それを見せることが強さだったりする' },
    { en: 'compassion wins', ja: '思いやりが勝つ。強さより優しさの方が長続きする' },
    { en: 'own your mistakes', ja: '失敗を認めろ。言い訳しないで' },
    { en: 'think outside the box', ja: '固定観念を捨てろ。箱の外で考えてみて' },
    { en: 'push your limits', ja: '限界を超えろ。タイピングでも同じこと' },
    { en: 'leave no regrets', ja: '後悔を残すな。やらない後悔の方が大きいよ' },
    { en: 'the greater good', ja: 'より大きな善のために。個人より全体を考えること' },
    { en: 'question everything', ja: 'すべてに疑問を持て。当たり前を疑う姿勢が大事' },
    { en: 'lead by example', ja: '背中で見せろ。口より行動で示してよ' },
    { en: 'redefine success', ja: '成功を定義し直せ。人と比べなくていい' },
    { en: 'nurture your growth', ja: '成長を大切に育てろ。放っておいたら育たない' },
    { en: 'bridge the gap', ja: 'ギャップを埋めろ。理想と現実の差を縮めること' },
    { en: 'take ownership', ja: '自分のこととして引き受けろ。他人事にしないで' },
    { en: 'seek the truth', ja: '真実を求めろ。表面だけで判断しないで' },
    { en: 'deliberate practice', ja: '意図的な練習。ただやるんじゃなくて考えてやること' },
    { en: 'cultivate gratitude', ja: '感謝の気持ちを育てろ。当たり前に感謝してよ' },
    { en: 'illuminate the path', ja: '道を照らせ。誰かの先を歩く人になってよ' },
    { en: 'fuel your passion', ja: '情熱に燃料を注げ。冷めさせないで' },
    { en: 'transcend the ordinary', ja: '普通を超えろ。平凡に甘んじないで' },
    { en: 'forge your destiny', ja: '運命を切り開け。待ってても来ないから' },
    { en: 'breathe and believe', ja: '息して信じろ。まず落ち着いて、それから前を向いて' },
    { en: 'unlock your potential', ja: '可能性を解放しろ。鍵はもう持ってるはず' },
    { en: 'face your fears', ja: '恐れと向き合え。逃げ続けると追いかけてくるから' },
    { en: 'honor the journey', ja: '旅そのものを大切に。結果だけが全てじゃない' },
    { en: 'clarity of purpose', ja: '目的の明確さ。何のためにやるか、わかってる？' },
    { en: 'spark meaningful change', ja: '意味のある変化を起こせ。小さくていいから' },
    { en: 'bold and fearless', ja: '大胆で恐れ知らず。そういう人になってほしい' },
    { en: 'embrace the unknown', ja: '未知を受け入れろ。知らないことは恥じゃない' },
    { en: 'infinite curiosity', ja: '終わりなき好奇心。持ち続けてよ、ずっと' },
    { en: 'quiet persistence', ja: '静かな粘り強さ。うるさくなくても続けることが大事' },
    { en: 'deliberate kindness', ja: '意識的な優しさ。自然にできなくても意識してやること' },
    { en: 'harness your strengths', ja: '強みを活かせ。弱点ばかり気にしないで' },
    { en: 'rewrite your story', ja: '自分の物語を書き直せ。過去は変えられないけど未来は変えられる' },
    { en: 'hold your ground', ja: 'ゆずるな。信念を曲げないで。でも頑固すぎもダメ' },
    { en: 'create with intention', ja: '意図を持って作れ。なんとなくじゃなくて目的を持って' },
    { en: 'aspire to inspire', ja: '誰かの刺激になることを目指せ。影響力を持つ人になって' },
    { en: 'walk your own path', ja: '自分の道を歩け。他人の真似ばかりしないで' },
    { en: 'patience is strength', ja: '忍耐は強さ。待てる人が最終的に勝つから' },
    { en: 'rise with the dawn', ja: '夜明けとともに立ち上がれ。起きるだけでもまず偉い' },
    { en: 'sharpen your focus', ja: '集中力を研ぎ澄ませ。ぼーっとしてる場合じゃない' },
    { en: 'champion your values', ja: '自分の価値観を守れ。何を大切にするか、ちゃんと決めて' },
    { en: 'build something real', ja: '本物を作れ。見せかけじゃなくて中身のあるものを' },
    { en: 'consistent effort', ja: '一貫した努力。気が向いたときだけじゃなくて毎日続けること' },
    { en: 'cherish the small things', ja: '小さなことを大切に。当たり前の幸せを見逃さないで' },
    { en: 'never stop wondering', ja: '不思議に思うことをやめるな。それが成長の源だから' },
    { en: 'define your legacy', ja: '自分の遺産を定義しろ。何を残したいか考えてる？' },
    { en: 'own your narrative', ja: '自分の物語の主人公でいろ。誰かのモブにならないで' },
    { en: 'make today count', ja: '今日を無駄にするな。昨日より少しだけ前に進んで' },
    { en: 'the world needs you', ja: '世界にはあなたが必要。大げさじゃなくてほんとに' },
  ],

  lv4: [
    { en: 'strategic implementation plan', ja: '戦略的実施計画。ビジネス用語、私でも難しい' },
    { en: 'collaborative innovation', ja: '協調的イノベーション。一緒に何か新しいこと作るやつ' },
    { en: 'comprehensive analysis', ja: '包括的分析。全部ひっくるめて調べること。面倒くさそう' },
    { en: 'sustainable development', ja: '持続可能な開発。SDGsって聞いたことある？' },
    { en: 'core competency', ja: 'コアコンピタンス。強みのこと。お兄ちゃんの強みって何？' },
    { en: 'paradigm shift', ja: 'パラダイムシフト。価値観がひっくり返ること。経験してみたい' },
    { en: 'proactive approach', ja: '積極的なアプローチ。受け身じゃなく自分から動くこと' },
    { en: 'stakeholder engagement', ja: 'ステークホルダーの関与。関係者みんなを巻き込むこと' },
    { en: 'due diligence', ja: 'デューデリジェンス。徹底的な調査のこと。投資の前にやるやつ' },
    { en: 'value proposition', ja: 'バリュープロポジション。何が価値なのか示すこと' },
    { en: 'disruptive technology', ja: '破壊的テクノロジー。業界をひっくり返す技術のこと' },
    { en: 'cross functional team', ja: '部門横断チーム。いろんな部署の人が集まるやつ' },
    { en: 'agile methodology', ja: 'アジャイル手法。素早く柔軟に開発するやり方' },
    { en: 'intellectual property', ja: '知的財産。アイデアや発明を守る権利のこと' },
    { en: 'return on investment', ja: '投資収益率。ROIって略す。元が取れてるか確認するやつ' },
    { en: 'organizational culture', ja: '組織文化。会社の雰囲気とか価値観のこと' },
    { en: 'performance metrics', ja: 'パフォーマンス指標。どれだけうまくいってるか測る数字' },
    { en: 'risk mitigation strategy', ja: 'リスク軽減戦略。うまくいかない可能性を減らすこと' },
    { en: 'market penetration', ja: '市場浸透。新しい市場に入り込むこと。難しそう' },
    { en: 'competitive advantage', ja: '競争優位性。他より優れてる部分のこと' },
    { en: 'scalable architecture', ja: 'スケーラブルなアーキテクチャ。大きくなっても耐えられる設計' },
    { en: 'data driven decision', ja: 'データに基づく決断。感情じゃなく数字で決めるやつ' },
    { en: 'seamless integration', ja: 'シームレスな統合。繋ぎ目なくまとめること。理想的' },
    { en: 'transparency and accountability', ja: '透明性と説明責任。隠し事しないでちゃんと話すこと' },
    { en: 'leverage existing resources', ja: '既存リソースを活用する。あるものをうまく使うこと' },
    { en: 'brand positioning', ja: 'ブランドポジショニング。どこに立ち位置を置くかのこと' },
    { en: 'continuous improvement', ja: '継続的改善。カイゼン。毎日少しずつよくすること' },
    { en: 'digital transformation', ja: 'デジタルトランスフォーメーション。DXって言うやつ' },
    { en: 'global supply chain', ja: 'グローバルサプライチェーン。世界中のモノの流れのこと' },
    { en: 'empathy driven design', ja: '共感を軸にした設計。ユーザーの気持ちになって作ること' },
    { en: 'executive summary', ja: 'エグゼクティブサマリー。偉い人向けの要約。読まれないやつ' },
    { en: 'benchmarking process', ja: 'ベンチマーキング。優れた事例を基準にして比べること' },
    { en: 'knowledge management', ja: 'ナレッジマネジメント。組織の知識をうまく管理すること' },
    { en: 'workforce optimization', ja: '人員最適化。人の配置をうまくやること。難しい' },
    { en: 'customer retention rate', ja: '顧客維持率。お客さんが離れないようにする指標' },
    { en: 'operational efficiency', ja: '業務効率。無駄をなくしてうまく動かすこと' },
    { en: 'innovation ecosystem', ja: 'イノベーションエコシステム。革新が生まれる環境のこと' },
    { en: 'thought leadership', ja: 'ソートリーダーシップ。その分野で影響力持つこと' },
    { en: 'bottom line impact', ja: '最終的な利益への影響。結局儲かるの？ってこと' },
    { en: 'cutting edge solution', ja: '最先端のソリューション。最新の解決策のこと' },
    { en: 'cross cultural communication', ja: '異文化コミュニケーション。文化が違う人と上手に話すこと' },
    { en: 'decision making framework', ja: '意思決定の枠組み。どうやって決断するかの仕組み' },
    { en: 'outcome based approach', ja: '成果ベースのアプローチ。結果で評価するやり方' },
    { en: 'enterprise resource planning', ja: 'ERPシステム。会社全体の資源を管理するソフト' },
    { en: 'strategic alignment', ja: '戦略的整合性。みんなが同じ方向を向いてること' },
    { en: 'psychological safety', ja: '心理的安全性。失敗を恐れず意見を言える環境のこと' },
    { en: 'pivot or persevere', ja: '方向転換か継続か。うまくいかないときの二択' },
    { en: 'minimum viable product', ja: '最小限の実行可能な製品。MVPって言う。まず出すこと' },
    { en: 'intrinsic motivation', ja: '内発的動機付け。外から言われなくても動けること。大事' },
    { en: 'exponential growth', ja: '指数関数的成長。急に爆発的に伸びること。憧れる' },
    { en: 'inclusive leadership', ja: 'インクルーシブなリーダーシップ。みんなを巻き込むリーダー像' },
    { en: 'long term vision', ja: '長期的ビジョン。先を見通した目標のこと。持ってる？' },
    { en: 'radical transparency', ja: '徹底した透明性。全部オープンにするやつ。勇気いる' },
    { en: 'iterative development', ja: '反復的な開発。少しずつ改善しながら作ること' },
    { en: 'conversion rate optimization', ja: 'コンバージョン率最適化。行動してもらう確率を上げること' },
    { en: 'economies of scale', ja: '規模の経済。大きくなるほどコストが下がること' },
    { en: 'high performance culture', ja: 'ハイパフォーマンスな文化。みんなが本気で取り組む組織' },
    { en: 'proactive communication', ja: '積極的なコミュニケーション。待たずに自分から伝えること' },
    { en: 'meaningful engagement', ja: '意味のある関与。表面だけじゃなく本質的に関わること' },
    { en: 'critical thinking skills', ja: '批判的思考スキル。言われたことをそのまま信じないこと' },
    { en: 'talent acquisition strategy', ja: '人材獲得戦略。優秀な人をどう採用するかの計画' },
    { en: 'revenue optimization model', ja: '収益最適化モデル。どうやって儲けを最大化するかの仕組み' },
    { en: 'go to market strategy', ja: '市場参入戦略。新しい商品をどう売り出すかの計画' },
    { en: 'human capital development', ja: '人的資本開発。人を育てることへの投資のこと' },
    { en: 'net promoter score', ja: 'ネットプロモータースコア。顧客がどれだけ勧めたいかの指標' },
    { en: 'omnichannel experience', ja: 'オムニチャネル体験。どの接点でも一貫した体験を提供すること' },
    { en: 'product market fit', ja: 'プロダクトマーケットフィット。製品と市場がぴったり合うこと' },
    { en: 'zero based budgeting', ja: 'ゼロベース予算。毎回ゼロから予算を組み直すやり方' },
    { en: 'stakeholder value creation', ja: 'ステークホルダーへの価値創出。関係者みんなに価値を届けること' },
    { en: 'first principles thinking', ja: 'ファーストプリンシプル思考。根本から考えるイーロン・マスク的発想' },
    { en: 'corporate social responsibility', ja: 'CSR。企業の社会的責任のこと。やってるふりだけの会社もある' },
    { en: 'machine learning pipeline', ja: '機械学習パイプライン。AIがデータを処理する流れのこと' },
    { en: 'user experience design', ja: 'UXデザイン。使う人の体験を中心に設計すること' },
    { en: 'service level agreement', ja: 'SLA。サービス品質の約束事。守らないと怒られる' },
    { en: 'compound annual growth rate', ja: 'CAGR。年間の複利成長率。投資でよく使う指標' },
    { en: 'total addressable market', ja: 'TAM。対象とする市場全体の規模のこと' },
    { en: 'behavioral economics', ja: '行動経済学。人が合理的じゃない選択をする理由を研究する学問' },
    { en: 'cognitive bias awareness', ja: '認知バイアスへの気づき。自分の思い込みに気づくこと' },
    { en: 'systems thinking approach', ja: 'システム思考。全体のつながりで物事を捉えるやり方' },
    { en: 'design sprint methodology', ja: 'デザインスプリント。5日間で解決策を検証するGoogleのやり方' },
    { en: 'growth hacking tactics', ja: 'グロースハック戦術。低コストで急成長させるための工夫' },
    { en: 'blue ocean strategy', ja: 'ブルーオーシャン戦略。競争のない市場を作り出すこと' },
    { en: 'emotional intelligence quotient', ja: 'EQ。感情を理解してコントロールする能力のこと' },
    { en: 'servant leadership model', ja: 'サーバントリーダーシップ。メンバーを支えることでリードするスタイル' },
    { en: 'scenario planning exercise', ja: 'シナリオプランニング。複数の未来を想定して準備すること' },
    { en: 'balanced scorecard framework', ja: 'バランスト・スコアカード。財務だけじゃない多角的な評価指標' },
    { en: 'network effect dynamics', ja: 'ネットワーク効果。使う人が増えるほど価値が上がる現象' },
    { en: 'predictive analytics platform', ja: '予測分析プラットフォーム。データから未来を予測するシステム' },
    { en: 'customer lifetime value', ja: '顧客生涯価値。一人のお客さんが生涯でもたらす利益のこと' },
    { en: 'workforce diversity initiative', ja: '多様性推進の取り組み。いろんな背景の人が活躍できる職場づくり' },
    { en: 'platform business model', ja: 'プラットフォームビジネスモデル。売り手と買い手をつなぐ場を作るやり方' },
    { en: 'value chain analysis', ja: 'バリューチェーン分析。どの工程で価値が生まれるかを分析すること' },
    { en: 'distributed team management', ja: '分散チームのマネジメント。リモートで働くチームをどう管理するか' },
    { en: 'customer success framework', ja: 'カスタマーサクセスの枠組み。お客さんが成功するよう支援する仕組み' },
    { en: 'market segmentation strategy', ja: '市場細分化戦略。顧客をグループに分けてそれぞれに対応すること' },
    { en: 'rapid prototyping process', ja: 'ラピッドプロトタイピング。素早く試作品を作って検証するプロセス' },
    { en: 'change management framework', ja: 'チェンジマネジメントの枠組み。組織の変化をうまく進める方法論' },
    { en: 'talent retention programs', ja: '人材定着プログラム。優秀な人が辞めないようにする施策' },
    { en: 'user acquisition funnel', ja: 'ユーザー獲得ファネル。新規ユーザーを集めて定着させるまでの流れ' },
    { en: 'brand equity measurement', ja: 'ブランドエクイティの測定。ブランドの価値をどう数値化するか' },
    { en: 'cross channel attribution', ja: 'クロスチャネルアトリビューション。どの接点が成果につながったか分析すること' },
    { en: 'product lifecycle management', ja: '製品ライフサイクル管理。製品の誕生から終わりまでを管理すること' },
    { en: 'lean startup methodology', ja: 'リーンスタートアップ。無駄をなくして素早く事業を立ち上げる方法' },
    { en: 'key performance indicators', ja: 'KPI。重要業績評価指標。目標達成度を測る数値のこと' },
    { en: 'demand generation strategy', ja: 'デマンドジェネレーション戦略。需要を作り出すためのマーケティング活動' },
    { en: 'organizational transformation', ja: '組織変革。会社の構造や文化を根本から変えること。大変なやつ' },
    { en: 'competitive intelligence gathering', ja: '競合情報収集。ライバル企業の動きを調査して戦略に活かすこと' },
    { en: 'customer journey mapping', ja: 'カスタマージャーニーマップ。お客さんの体験全体を可視化すること' },
    { en: 'agile transformation roadmap', ja: 'アジャイル変革ロードマップ。組織全体をアジャイルに変えていく計画' },
    { en: 'leadership development pipeline', ja: 'リーダー育成のパイプライン。次世代のリーダーを継続的に育てる仕組み' },
    { en: 'dynamic pricing algorithm', ja: '動的価格設定アルゴリズム。需要に応じてリアルタイムで価格を変えるやつ' },
    { en: 'knowledge transfer protocol', ja: 'ナレッジ移転プロトコル。知識や経験を組織内で共有する手順のこと' },
    { en: 'strategic workforce planning', ja: '戦略的人員計画。将来の事業に必要な人材をどう確保するかの計画' },
    { en: 'enterprise architecture design', ja: 'エンタープライズアーキテクチャ設計。会社全体のシステム構造を設計すること' },
    { en: 'omnichannel retail strategy', ja: 'オムニチャネル小売戦略。店舗とオンラインを統合した販売戦略' },
    { en: 'innovation management system', ja: 'イノベーション管理システム。新しいアイデアを組織的に育てる仕組み' },
    { en: 'real time data analytics', ja: 'リアルタイムデータ分析。今この瞬間のデータをすぐに分析すること' },
    { en: 'corporate venture capital', ja: 'コーポレートベンチャーキャピタル。大企業がスタートアップに投資すること' },
    { en: 'multi stakeholder governance', ja: 'マルチステークホルダーガバナンス。複数の利害関係者で意思決定する仕組み' },
    { en: 'ecosystem partnership strategy', ja: 'エコシステムパートナーシップ戦略。協力関係で新しい価値を生み出すこと' },
    { en: 'transformational leadership style', ja: '変革型リーダーシップ。ビジョンを示してメンバーを変革に導くスタイル' },
  ],
  final: [
    { en: 'We observe today not a victory of party, but a celebration of freedom', ja: '今日は党の勝利じゃなくて自由のお祭りだって。なんか急にでかいこと言い出した' },
    { en: 'symbolizing an end, as well as a beginning', ja: '終わりであり始まりでもある、って。どっちなの、はっきりして' },
    { en: 'signifying renewal, as well as change', ja: '刷新と変化を意味する。変化って言葉好きな人多いよね、みんな' },
    { en: 'For I have sworn before you and Almighty God the same solemn oath our forebears prescribed nearly a century and three-quarters ago', ja: '神と皆さんの前で誓いを立てた。175年前と同じ誓い。重いな' },
    { en: 'The world is very different now', ja: '世界は今やとても違う。急に話変わった。でもそうだよね' },
    { en: 'For man holds in his mortal hands the power to abolish all forms of human poverty and all forms of human life', ja: '人間は貧困を消す力も、命を全部消す力も持ってる。怖いこと言う' },
    { en: 'And yet the same revolutionary beliefs for which our forebears fought are still at issue around the globe', ja: '先人が戦った理念はまだ世界で問われてる。解決してないじゃん' },
    { en: 'the belief that the rights of man come not from the generosity of the state, but from the hand of God', ja: '人権は国家の気まぐれじゃなくて神から来る。なるほど、神推しなのね' },
    { en: 'We dare not forget today that we are the heirs of that first revolution', ja: '私たちは最初の革命の後継者だということを忘れてはならない。重い自覚' },
    { en: 'Let the word go forth from this time and place, to friend and foe alike', ja: '友にも敵にも、この時この場所から言葉を発せよ。全方位に宣言する気満々' },
    { en: 'that the torch has been passed to a new generation of Americans', ja: 'たいまつが新しい世代のアメリカ人に渡された。バトンタッチね' },
    { en: 'born in this century, tempered by war, disciplined by a hard and bitter peace', ja: '今世紀に生まれ、戦争で鍛えられ、苦い平和で訓練された。壮絶な自己紹介' },
    { en: 'proud of our ancient heritage', ja: '古い遺産を誇りに思う。歴史を大切にしてるんだね' },
    { en: 'and unwilling to witness or permit the slow undoing of those human rights to which this Nation has always been committed', ja: '人権がじわじわ消えていくのを見たくないし許したくない。その気持ちわかる' },
    { en: 'and to which we are committed today at home and around the world', ja: '国内でも世界中でも、今日もその人権にコミットしてる。有言実行してほしい' },
    { en: 'Let every nation know, whether it wishes us well or ill', ja: '私たちを好きでも嫌いでも、すべての国に知ってほしい。強気だな' },
    { en: 'that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe', ja: 'どんな代価も払う、どんな重荷も背負う、どんな苦難も乗り越える。全部やるって言ってる' },
    { en: 'in order to assure the survival and the success of liberty', ja: '自由の存続と成功を確かなものにするために。自由のためなら何でもする人' },
    { en: 'This much we pledge, and more', ja: 'これだけは約束する、それ以上も。プラスアルファが気になる' },
    { en: 'To those old allies whose cultural and spiritual origins we share', ja: '文化的・精神的起源を共にする古い同盟国へ。仲間に向けての言葉' },
    { en: 'we pledge the loyalty of faithful friends', ja: '誠実な友の忠誠を誓う。友情は大事だよね' },
    { en: 'United, there is little we cannot do in a host of cooperative ventures', ja: '団結すれば、協力してできないことはほとんどない。みんなの力は強い' },
    { en: 'Divided, there is little we can do', ja: 'でも分裂したら、ほとんど何もできない。シンプルだけど核心ついてる' },
    { en: 'for we dare not meet a powerful challenge at odds and split asunder', ja: 'バラバラになって強大な挑戦に立ち向かう勇気はないから。正直だな' },
    { en: 'To those new States whom we welcome to the ranks of the free', ja: '自由の仲間入りをした新しい国々へ。新参者へのメッセージ' },
    { en: 'we pledge our word that one form of colonial control shall not have passed away merely to be replaced by a far more iron tyranny', ja: '植民地支配が消えても、もっとひどい独裁に変わるだけじゃダメだって言ってる' },
    { en: 'We shall not always expect to find them supporting our every policy', ja: 'いつも私たちの政策を支持してくれるとは思ってない。現実的だな' },
    { en: 'but we shall always hope to find them strongly supporting their own freedom', ja: 'でも彼ら自身の自由を強く支持してくれることは期待してる。自立してほしい' },
    { en: 'To those peoples in the huts and villages across the globe struggling to break the bonds of mass misery', ja: '世界中の小屋や村で、大きな不幸から抜け出そうとしている人々へ' },
    { en: 'we pledge our best efforts to help them help themselves', ja: '自分たちで立ち上がれるよう、最善を尽くして助けると誓う。魚を与えるんじゃなくて' },
    { en: 'for whatever period is required', ja: '必要な期間、ずっと。期限なし宣言。太っ腹' },
    { en: 'not because the Communists may be doing it', ja: 'コミュニストがやってるからじゃない。対抗意識じゃなくて' },
    { en: 'not because we seek their votes', ja: '票が欲しいからでもない。選挙目当てでもない。へえ' },
    { en: 'but because it is right', ja: 'ただ、それが正しいことだから。シンプルすぎて逆に信用できる' },
    { en: 'If a free society cannot help the many who are poor', ja: '自由な社会が、貧しい多数を助けられないなら' },
    { en: 'it cannot save the few who are rich', ja: '裕福な少数を救うこともできない。格差への警告だな' },
    { en: 'To our sister republics south of our border', ja: '国境の南にある姉妹共和国へ。中南米向けのメッセージ' },
    { en: 'we offer a special pledge', ja: '特別な誓いを捧げる。VIP扱いね' },
    { en: 'to convert our good words into good deeds', ja: '良い言葉を良い行動に変えること。言うだけじゃなくて行動するってこと' },
    { en: 'in a new alliance for progress', ja: '新しい進歩のための同盟の中で。アライアンス・フォー・プログレス、実際に作った' },
    { en: 'to assist free men and free governments in casting off the chains of poverty', ja: '自由な人々と政府が貧困の鎖を断ち切るのを助けること。鎖って表現が重い' },
    { en: 'But this peaceful revolution of hope cannot become the prey of hostile powers', ja: '希望の平和的革命が、敵対的な勢力の獲物になってはいけない。守らなきゃいけないものがある' },
    { en: 'Let all our neighbors know that we shall join with them to oppose aggression or subversion anywhere in the Americas', ja: '南北アメリカ大陸のどこでも侵略や破壊工作には立ち向かうと近隣諸国に知らせよ' },
    { en: 'And let every other power know that this Hemisphere intends to remain the master of its own house', ja: '他のすべての大国に、この半球は自分の家の主人であり続けるつもりだと知らせよ' },
    { en: 'To that world assembly of sovereign states, the United Nations', ja: '主権国家の世界的集会、国際連合へ。国連への言及' },
    { en: 'our last best hope in an age where the instruments of war have far outpaced the instruments of peace', ja: '戦争の道具が平和の道具をはるかに超えてしまった時代の、最後の最善の希望。国連への期待が重い' },
    { en: 'we renew our pledge of support', ja: '支持の誓いを新たにする。改めて約束する感じ' },
    { en: 'to prevent it from becoming merely a forum for invective', ja: '単なる非難の場にならないよう。批判合戦になってほしくないってこと' },
    { en: 'to strengthen its shield of the new and the weak', ja: '新しく弱い国々を守る盾を強化するために。弱者を守る姿勢' },
    { en: 'and to enlarge the area in which its writ may run', ja: 'その決定が及ぶ範囲を広げるために。影響力を拡大させたい' },
    { en: 'Finally, to those nations who would make themselves our adversary', ja: '最後に、私たちの敵になろうとしている国々へ。敵への直接メッセージ' },
    { en: 'we offer not a pledge but a request', ja: '誓いではなく、お願いをする。意外と穏やか' },
    { en: 'that both sides begin anew the quest for peace', ja: '両側が平和を求める旅を新たに始めることを。一緒に始めようって言ってる' },
    { en: 'before the dark powers of destruction unleashed by science engulf all humanity in planned or accidental self-destruction', ja: '科学が解き放った破壊の暗い力が、計画的・偶発的な自滅で人類を飲み込む前に' },
    { en: 'We dare not tempt them with weakness', ja: '弱さで彼らを誘惑してはならない。弱く見せたらダメ' },
    { en: 'For only when our arms are sufficient beyond doubt can we be certain beyond doubt that they will never be employed', ja: '武力が十分すぎるほどあるときだけ、それが使われないと確信できる。抑止力の逆説' },
    { en: 'But neither can two great and powerful groups of nations take comfort from our present course', ja: 'でも二つの大きな強国グループが、今の路線から安心感を得ることもできない' },
    { en: 'both sides overburdened by the cost of modern weapons', ja: '両側とも現代兵器のコストで疲弊してる。お金かかりすぎ問題' },
    { en: 'both rightly alarmed by the steady spread of the deadly atom', ja: '両側とも、deadly atomの着実な広がりに正しく警戒してる。deadly atomって言い方が怖い' },
    { en: 'yet both racing to alter that uncertain balance of terror that stays the hand of mankind\'s final war', ja: 'それでも両側とも、最終戦争を防いでいる恐怖の不確かなバランスを変えようと競走してる' },
    { en: 'So let us begin anew', ja: 'では新たに始めよう。ここから転換点の雰囲気' },
    { en: 'remembering on both sides that civility is not a sign of weakness', ja: '両側とも、礼儀正しさは弱さのサインじゃないことを覚えておきながら。丁寧さは弱くない' },
    { en: 'and sincerity is always subject to proof', ja: '誠意は常に証明が必要だ。言葉より行動で示せってこと' },
    { en: 'Let us never negotiate out of fear', ja: '恐れから交渉することは決してしない。弱い立場で譲歩しないって宣言' },
    { en: 'But let us never fear to negotiate', ja: 'でも交渉を恐れることもしない。対話は続けるってこと。バランスが大事' },
    { en: 'Let both sides explore what problems unite us instead of belaboring those problems which divide us', ja: '両側は、分断する問題をこねくり回すより、団結させる問題を探ろう' },
    { en: 'Let both sides, for the first time, formulate serious and precise proposals for the inspection and control of arms', ja: '両側は初めて、軍備の査察と管理のための真剣で正確な提案をしよう' },
    { en: 'and bring the absolute power to destroy other nations under the absolute control of all nations', ja: '他国を破壊する絶対的な力を、すべての国の絶対的な管理下に置こう' },
    { en: 'Let both sides seek to invoke the wonders of science instead of its terrors', ja: '両側とも、科学の恐怖じゃなくて驚異を呼び起こすよう努めよう' },
    { en: 'Together let us explore the stars, conquer the deserts, eradicate disease', ja: '一緒に星を探索し、砂漠を征服し、病気を根絶しよう。壮大な共同作業' },
    { en: 'tap the ocean depths, and encourage the arts and commerce', ja: '海の深さを開拓し、芸術と商業を奨励しよう。全部やるリスト' },
    { en: 'Let both sides unite to heed in all corners of the earth the command of Isaiah', ja: '両側は地球のあらゆる場所でイザヤの命令に従うために団結しよう。聖書の引用' },
    { en: 'to undo the heavy burdens and let the oppressed go free', ja: '重い重荷を取り除き、虐げられた人々を自由にせよ。イザヤ書から。重い言葉だ' },
    { en: 'And if a beachhead of cooperation may push back the jungle of suspicion', ja: '協力の橋頭堡が疑いのジャングルを押し返すことができれば。比喩が凝ってる' },
    { en: 'let both sides join in creating a new endeavor', ja: '両側が新しい取り組みを作るために協力しよう' },
    { en: 'not a new balance of power', ja: '新しい力のバランスではなく。バランス・オブ・パワーじゃないって' },
    { en: 'but a new world of law', ja: 'でも法の新しい世界を。ルールに基づく世界秩序のこと' },
    { en: 'where the strong are just and the weak secure and the peace preserved', ja: '強者が公正で、弱者が安全で、平和が守られる世界。理想だけど美しい' },
    { en: 'All this will not be finished in the first hundred days', ja: 'これらは最初の百日間では終わらない。長期戦を覚悟してる' },
    { en: 'Nor will it be finished in the first thousand days', ja: '最初の千日間でも終わらない。まだまだ続く' },
    { en: 'nor in the life of this Administration', ja: 'この政権の任期中でも終わらない。自分の代では無理かもって認めてる' },
    { en: 'nor even perhaps in our lifetime on this planet', ja: 'もしかしたら私たちが生きている間でも終わらないかもしれない。でも続ける' },
    { en: 'But let us begin', ja: 'でも、始めよう。このシンプルさがかっこいい' },
    { en: 'In your hands, my fellow citizens, more than in mine', ja: '市民の皆さんの手の中に、私の手よりも多くが。責任を国民に渡してる' },
    { en: 'will rest the final success or failure of our course', ja: '私たちの進路の最終的な成功か失敗かがかかっている。重い責任を委ねた' },
    { en: 'Since this country was founded, each generation of Americans has been summoned to give testimony to its national loyalty', ja: 'この国が建国されて以来、各世代のアメリカ人は国への忠誠を証明するよう召集されてきた' },
    { en: 'The graves of young Americans who answered the call to service surround the globe', ja: '召集に応えた若いアメリカ人のお墓が世界中にある。重すぎる事実' },
    { en: 'Now the trumpet summons us again', ja: 'トランペットが私たちを再び召集している。また呼ばれてる' },
    { en: 'not as a call to bear arms, though arms we need', ja: '武器が必要だとしても、武器を持てという召集ではない。戦争への呼びかけじゃない' },
    { en: 'not as a call to battle, though embattled we are', ja: '戦いの最中にいるとしても、戦いへの召集でもない' },
    { en: 'but a call to bear the burden of a long twilight struggle', ja: '長い薄明の戦いの重荷を担うための召集だ。twilight struggle、詩的な表現' },
    { en: 'year in and year out, rejoicing in hope, patient in tribulation', ja: '年がら年中、希望に喜び、苦難に忍耐して。終わりのない戦いの覚悟' },
    { en: 'a struggle against the common enemies of man', ja: '人類共通の敵との戦い。共通の敵を設定することで団結させる' },
    { en: 'tyranny, poverty, disease, and war itself', ja: '専制、貧困、病気、そして戦争そのもの。具体的に挙げてくれた' },
    { en: 'Can we forge against these enemies a grand and global alliance', ja: 'これらの敵に対して、壮大で世界的な同盟を作れるか？問いかけ形式' },
    { en: 'North and South, East and West', ja: '北と南、東と西。全方位の団結' },
    { en: 'that can assure a more fruitful life for all mankind', ja: 'すべての人類により実りある生活を保証できる同盟を。全員のためという視点' },
    { en: 'Will you join in that historic effort', ja: 'この歴史的な取り組みに参加してくれますか？直接問いかけ。重い' },
    { en: 'In the long history of the world, only a few generations have been granted the role of defending freedom in its hour of maximum danger', ja: '世界の長い歴史の中で、最大の危機の時に自由を守る役割を与えられた世代はほんのわずかだ' },
    { en: 'I do not shrink from this responsibility', ja: 'この責任から逃げない。堂々と宣言' },
    { en: 'I welcome it', ja: 'むしろ歓迎する。かっこよすぎ' },
    { en: 'I do not believe that any of us would exchange places with any other people or any other generation', ja: '他のどんな人や世代とも場所を交換しようとは思わない。今この時代に生きることを誇りに思ってる' },
    { en: 'The energy, the faith, the devotion which we bring to this endeavor will light our country and all who serve it', ja: 'この取り組みに捧げるエネルギー、信念、献身が国と仕える人々を照らす' },
    { en: 'and the glow from that fire can truly light the world', ja: 'その炎の輝きは真に世界を照らすことができる。壮大な締めへの前振り' },
    { en: 'And so, my fellow Americans: ask not what your country can do for you', ja: 'だから、アメリカ市民の皆さん、国があなたに何をしてくれるかを問うな。この名言来た' },
    { en: 'ask what you can do for your country', ja: 'あなたが国に何をできるかを問え。名言の後半。重い' },
    { en: 'My fellow citizens of the world: ask not what America will do for you', ja: '世界市民の皆さん、アメリカが何をしてくれるかを問うな' },
    { en: 'but what together we can do for the freedom of man', ja: '一緒に人類の自由のために何ができるかを問え。全人類へのメッセージ' },
    { en: 'Finally, whether you are citizens of America or citizens of the world', ja: '最後に、アメリカ市民であれ世界市民であれ' },
    { en: 'ask of us the same high standards of strength and sacrifice which we ask of you', ja: '私たちがあなたに求めるのと同じ高い基準の強さと犠牲を、私たちにも求めてください' },
    { en: 'With a good conscience our only sure reward', ja: '良心だけが確かな報酬として。見返りを求めない姿勢' },
    { en: 'with history the final judge of our deeds', ja: '歴史が私たちの行動の最終的な審判者として。後世に判断を委ねる' },
    { en: 'let us go forth to lead the land we love', ja: '私たちが愛する国を導くために出発しよう。愛国心を前面に' },
    { en: 'asking His blessing and His help', ja: '神の祝福と助けを求めながら。締めも神推し' },
    { en: 'but knowing that here on earth God\'s work must truly be our own', ja: 'でもここ地球上では、神の仕事は本当に私たち自身のものでなければならないことを知りながら。結局自分たちでやるしかない' },
  ],
};

const RESULT_MESSAGES = [
  // ==============================
  // level 1-3: ツン100%（デレなし）
  // ==============================

  // Lv1 / コンボ低 / ミス少
  { level: 1, maxCombo: [0, 49], miss: [0, 3], dere: false,
    text: 'まあ…ミスは少なかったね。それだけ。次はもっとやって' },
  { level: 1, maxCombo: [0, 49], miss: [4, 10], dere: false,
    text: 'ミス多いし、コンボも全然だし。何しに来たの？' },
  { level: 1, maxCombo: [0, 49], miss: [11, 19], dere: false,
    text: 'こんなにミスして恥ずかしくないの？ねえ、恥ずかしくない？' },
  { level: 1, maxCombo: [0, 49], miss: [20, 999], dere: false,
    text: 'ゲームオーバー…。まあLv1だし、初めてだし。言い訳はそれだけ許してあげる' },

  // Lv1 / コンボ中 / ミス少
  { level: 1, maxCombo: [50, 199], miss: [0, 3], dere: false,
    text: 'コンボ出てるじゃん。まぐれ？まぐれだよね。次も出せたら認めてあげる' },
  { level: 1, maxCombo: [50, 199], miss: [4, 10], dere: false,
    text: 'コンボはそこそこだけどミスも多い。どっちつかずって一番ダサいよ' },
  { level: 1, maxCombo: [50, 199], miss: [11, 19], dere: false,
    text: 'コンボ出てもミスがね。安定してないんだよ、あなたって' },
  { level: 1, maxCombo: [50, 199], miss: [20, 999], dere: false,
    text: 'コンボ出てたのにゲームオーバー。もったいなすぎて見てられない' },

  // Lv1 / コンボ高
  { level: 1, maxCombo: [200, 999], miss: [0, 6], dere: false,
    text: '200コンボ出てLv1で終わってるって、それどういうこと。もっと上目指しなよ' },
  { level: 1, maxCombo: [200, 999], miss: [7, 999], dere: false,
    text: 'コンボは出たけど結局Lv1。ポテンシャルの無駄遣いすぎる' },

  // Lv2 / コンボ低 / ミス少
  { level: 2, maxCombo: [0, 49], miss: [0, 3], dere: false,
    text: 'Lv2まで来て、コンボ50以下。丁寧だけど遅い。タイピングは速さも大事' },
  { level: 2, maxCombo: [0, 49], miss: [4, 10], dere: false,
    text: 'Lv2でこのコンボとミス数。中途半端の極みだね、悪い意味で' },
  { level: 2, maxCombo: [0, 49], miss: [11, 19], dere: false,
    text: 'Lv2でこんなにミスするの。もう少し落ち着いてよ、あわてんぼさん' },
  { level: 2, maxCombo: [0, 49], miss: [20, 999], dere: false,
    text: 'Lv2でゲームオーバーか。まあ、Lv1は突破したんだから少しは成長したかな。少しだけ' },

  // Lv2 / コンボ中
  { level: 2, maxCombo: [50, 199], miss: [0, 6], dere: false,
    text: 'Lv2でコンボもそこそこ、ミスも少ない。普通。普通ってことね' },
  { level: 2, maxCombo: [50, 199], miss: [7, 19], dere: false,
    text: 'Lv2、コンボ中くらい、ミス多め。バランス悪いんだよな。どっちか伸ばして' },
  { level: 2, maxCombo: [50, 199], miss: [20, 999], dere: false,
    text: 'ゲームオーバーはまずいでしょ。Lv2で。もう少し頑張れるはずだけどな' },

  // Lv2 / コンボ高
  { level: 2, maxCombo: [200, 999], miss: [0, 6], dere: false,
    text: '200コンボ出てLv2止まり。もったいない。もっと上に行けたはず' },
  { level: 2, maxCombo: [200, 999], miss: [7, 999], dere: false,
    text: 'コンボは出たけど、ミスのせいで止まったね。コンボを守れなかった結果' },

  // Lv3 / コンボ低 / ミス少
  { level: 3, maxCombo: [0, 49], miss: [0, 3], dere: false,
    text: 'Lv3まで来た。認める。でもコンボが低い。慎重すぎ、もっと攻めてよ' },
  { level: 3, maxCombo: [0, 49], miss: [4, 10], dere: false,
    text: 'Lv3まで来れたのに、コンボもミスも微妙。半分くらいの力しか出てないんじゃない？' },
  { level: 3, maxCombo: [0, 49], miss: [11, 19], dere: false,
    text: 'Lv3でこのミス数は多い。高校英語レベルで詰まってたら先が思いやられる' },
  { level: 3, maxCombo: [0, 49], miss: [20, 999], dere: false,
    text: 'Lv3でゲームオーバー。まあ、ここまで来たことは評価してあげる。評価だけ' },

  // Lv3 / コンボ中
  { level: 3, maxCombo: [50, 199], miss: [0, 6], dere: false,
    text: 'Lv3でこのコンボとミス数なら、まあ…及第点。及第点ね。ぎりぎりの' },
  { level: 3, maxCombo: [50, 199], miss: [7, 19], dere: false,
    text: 'コンボはそこそこ出てる。ミスさえなければね。ミスさえなければ！' },
  { level: 3, maxCombo: [50, 199], miss: [20, 999], dere: false,
    text: 'Lv3でゲームオーバー。ここまで来て終わるのはもったいないと思う、私は' },

  // Lv3 / コンボ高
  { level: 3, maxCombo: [200, 999], miss: [0, 6], dere: false,
    text: '200コンボ以上出してLv3。実力はあるのに止まってる。なんで？練習不足？' },
  { level: 3, maxCombo: [200, 999], miss: [7, 999], dere: false,
    text: 'コンボは申し分ない。ミスが足引っ張ってる。惜しいんだよ、本当に惜しい' },

  // Lv3 / 1000コンボ
  { level: 3, maxCombo: [1000, 9999], miss: [0, 999], dere: false,
    text: '1000コンボ出てLv3止まり。意味わかんない。その実力でなんで止まるの' },

  // ==============================
  // level 4: デレあり
  // ==============================

  // Lv4 / コンボ低 / ミス少
  { level: 4, maxCombo: [0, 49], miss: [0, 3], dere: true,
    text: 'Lv4まで来たじゃん…。す、すごいとは言ってないけど、まあ、ね。来たのは事実' },
  { level: 4, maxCombo: [0, 49], miss: [4, 10], dere: true,
    text: 'Lv4ね。ビジネス英語まで打てたってことじゃん。ちょっとだけ見直したかも' },
  { level: 4, maxCombo: [0, 49], miss: [11, 19], dere: true,
    text: 'Lv4まで来てミスが多い。でもLv4まで来たことは…認める。一応' },
  { level: 4, maxCombo: [0, 49], miss: [20, 999], dere: true,
    text: 'ゲームオーバーだけどLv4で…。頑張ったじゃん。言ってあげる、頑張ったって' },

  // Lv4 / コンボ中
  { level: 4, maxCombo: [50, 199], miss: [0, 6], dere: true,
    text: 'Lv4でこのスコア。す、すごいじゃん…。別に感動とかしてないけど、まあ' },
  { level: 4, maxCombo: [50, 199], miss: [7, 19], dere: true,
    text: 'Lv4まで来れた。コンボも出てる。ミスが惜しい。でも、よく頑張ったと思う' },
  { level: 4, maxCombo: [50, 199], miss: [20, 999], dere: true,
    text: 'Lv4でゲームオーバー。でも…ここまで来たんだからね。負けじゃないと思う' },

  // Lv4 / コンボ高
  { level: 4, maxCombo: [200, 999], miss: [0, 6], dere: true,
    text: '200コンボ以上でLv4。ちょっと待って、本当にすごいじゃん…。言っていい？すごい' },
  { level: 4, maxCombo: [200, 999], miss: [7, 19], dere: true,
    text: 'コンボすごい出てる。ミスはあったけど、それでもLv4でこれは…認める、完全に' },
  { level: 4, maxCombo: [200, 999], miss: [20, 999], dere: true,
    text: 'コンボ200以上でLv4。ゲームオーバーでも文句言えない。十分戦った' },

  // Lv4 / 1000コンボ
  { level: 4, maxCombo: [1000, 9999], miss: [0, 6], dere: true,
    text: '1000コンボ…！？Lv4で！？お兄ちゃん、本当に…本当にすごいよ。言っちゃった' },
  { level: 4, maxCombo: [1000, 9999], miss: [7, 999], dere: true,
    text: '1000コンボ出てLv4。ミスはあったけど…それでもこれは本物だよ。認める' },

  // ==============================
  // level 5: FINAL完走（大好きモード）
  // ==============================

  // FINAL完走 / コンボ低 / ミスあり
  { level: 5, maxCombo: [0, 49], miss: [1, 6], dere: true,
    text: 'JFK全文打ち切った…。ミスはあったけど、完走した。お兄ちゃん、すごいよ。普通にすごい' },
  { level: 5, maxCombo: [0, 49], miss: [7, 19], dere: true,
    text: 'FINAL完走！ミスは多かったけど、最後まで諦めなかった。それが一番大事だと思う' },
  { level: 5, maxCombo: [0, 49], miss: [20, 999], dere: true,
    text: 'ゲームオーバーでもFINALまで来た。ケネディ打ち切ったのか…。なんか、感動した' },

  // FINAL完走 / コンボ中
  { level: 5, maxCombo: [50, 199], miss: [1, 6], dere: true,
    text: 'FINAL完走してコンボも出て。お兄ちゃん…今日ちょっとかっこよかった。ちょっとだけ' },
  { level: 5, maxCombo: [50, 199], miss: [7, 19], dere: true,
    text: 'JFK打ち切った。ミスはあるけど、完走した事実は消えない。誇っていいよ、本当に' },
  { level: 5, maxCombo: [50, 199], miss: [20, 999], dere: true,
    text: 'FINALまで到達してゲームオーバー。でも…ここまで来ただけで十分すごい' },

  // FINAL完走 / コンボ高
  { level: 5, maxCombo: [200, 999], miss: [1, 6], dere: true,
    text: 'FINAL完走で200コンボ以上！お兄ちゃんケネディ打ち切ったんだね…。なんか泣きそう' },
  { level: 5, maxCombo: [200, 999], miss: [7, 19], dere: true,
    text: '200コンボ以上でFINAL。ミスはあったけど、それでもこれは…本物の実力だよ' },
  { level: 5, maxCombo: [200, 999], miss: [20, 999], dere: true,
    text: 'コンボ200以上でFINAL到達。ゲームオーバーでもこれだけ戦えたなら十分' },

  // FINAL完走 / 1000コンボ
  { level: 5, maxCombo: [1000, 9999], miss: [1, 999], dere: true,
    text: '1000コンボでFINAL…。お兄ちゃん、ケネディ全部打ち切って1000コンボ。言葉が出ない。本当に' },

  // ==============================
  // ノーミス完走（最高レアリティ）
  // ==============================
  { level: 5, maxCombo: [0, 9999], miss: [0, 0], dere: true,
    text: '私お兄ちゃんのお嫁さんになる' },
];

